name: Build and deploy Sphinx docs to GitHub Pages

on:
  push:
    branches:
      - dev    # change to your default branch if different
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
  
      - name: Install GFortran Linux
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc g++  gfortran python3-devel python3-numpy swig
          
      - name: configure_build_check
        run: |
          # build and run unit tests
          cmake -S . -B BUILD -DHOPPET_BUILD_PYINTERFACE=ON 
          cmake --build BUILD -j 4
          sudo cmake --install BUILD
          ctest --test-dir BUILD -j 4 --output-on-failure

          # now try running some python examples, checking the output matches the expected output
          scripts/check python3 example_py/tabulation_example.py
          scripts/check python3 example_py/tabulation_example_qed.py
          scripts/check python3 example_py/structure_functions_example.py

      #- name: Set up Python
      #  uses: actions/setup-python@v4
      #  with:
      #    python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/python-auto/requirements.txt

      - name: Build Sphinx HTML
        run: |
          sphinx-build -b html docs/python-auto/source docs/python-auto/_build/html
          # or use: make -C docs html

      - name: Upload artifact (optional, for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-html
          path: docs/python-auto/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAGES_PAT }}
          publish_branch: gh-pages
          publish_dir: ./docs/python-auto/_build/html
          # you can set commit_name, commit_email if desired
