name: Build and deploy Sphinx docs to GitHub Pages

on:
  push:
    branches:
      - dev    # change to your default branch if different
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/python-auto/requirements.txt
          pip install scikit-build-core swig build
          pip uninstall ninja -y || echo "ninja removed"
          rm /usr/local/bin/ninja || echo "ninja binary removed"
          python -m build
          pip install ./dist/hoppet-*.whl

      - name: Build Sphinx HTML
        run: |
          sphinx-build -b html docs/python-auto/source docs/python-auto/_build/html
          # or use: make -C docs html

      - name: Upload artifact (optional, for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-html
          path: docs/python-auto/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAGES_PAT }}
          publish_branch: gh-pages
          publish_dir: ./docs/python-auto/_build/html
          # you can set commit_name, commit_email if desired
